direction.o:	direction.cc direction.h

fwdorbwd.o:	fwdorbwd.cc fwdorbwd.h

phasepercycle.o:	phasepercycle.cc phasepercycle.h

tickperphase.o:	tickperphase.cc tickperphase.h

tickpercycle.o:	tickpercycle.cc tickpercycle.h rodtype.h fwdorbwd.h

voxelcoordinant.o:	voxelcoordinant.cc voxelcoordinant.h volume.h

fblkstate.o:	fblkstate.cc fblkstate.h

rblkstate.o:	rblkstate.cc rblkstate.h

voxeltype.o:	voxeltype.cc voxeltype.h

locktype.o:	locktype.cc locktype.h

lockstate.o:	lockstate.cc lockstate.h

datatype.o:	datatype.cc datatype.h

datastate.o:	datastate.cc datastate.h

blockstate.o:	blockstate.cc blockstate.h

rodtype.o:	rodtype.cc rodtype.h voxeltype.h tickpercycle.h direction.h

voxel.o:	voxel.cc voxel.h voxeltype.h rodtype.h \
		locktype.h lockstate.h datatype.h datastate.h \
		blockstate.h direction.h

scenario.o:	scenario.cc scenario.h tickpercycle.h voxel.h direction.h \
		voxelcoordinant.h

